spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistic_db
    username: root
    password: Oportoeumanacao1893@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
